INSERT INTO USUARIO (NOMBRE, PASSWORD) VALUES ('SERGIO', '1234');
INSERT INTO USUARIO (NOMBRE, PASSWORD) VALUES ('MARIBEL', '5678');
INSERT INTO USUARIO (NOMBRE, PASSWORD) VALUES ('PACO', '9123');

INSERT INTO ARTICULO (NOMBRE, PRECIO, STOCK) VALUES ('NIKE AIR ZOOM PEGASUS', 116.99, 50);
INSERT INTO ARTICULO (NOMBRE, PRECIO, STOCK) VALUES ('NIKE REVOLUTION 5', 49.99, 50);
INSERT INTO ARTICULO (NOMBRE, PRECIO, STOCK) VALUES ('ASICS DYNAFLITE 4', 99, 25);
INSERT INTO ARTICULO (NOMBRE, PRECIO, STOCK) VALUES ('ASICS GEL TRABUCO 9', 118, 30);
INSERT INTO ARTICULO (NOMBRE, PRECIO, STOCK) VALUES ('ASICS DYNAFLITE 4', 99, 25);
INSERT INTO ARTICULO (NOMBRE, PRECIO, STOCK) VALUES ('ADIDAS GLIDE 4 ST M', 105.99, 30);
INSERT INTO ARTICULO (NOMBRE, PRECIO, STOCK) VALUES ('ADIDAS SOLAR BOOST 3 M', 119.99, 30);

INSERT INTO PEDIDO (FECHA, NOMBRE, USUARIO_ID) VALUES ('20201125', 'PEDIDO 1', 1);
INSERT INTO PEDIDO (FECHA, NOMBRE, USUARIO_ID) VALUES ('20201124', 'PEDIDO 2', 2);
INSERT INTO PEDIDO (FECHA, NOMBRE, USUARIO_ID) VALUES ('20201123', 'PEDIDO 3', 3);

INSERT INTO PEDIDO_ARTICULO (CANTIDAD, ARTICULO_ID, PEDIDO_ID) VALUES (1, 1, 1);
INSERT INTO PEDIDO_ARTICULO (CANTIDAD, ARTICULO_ID, PEDIDO_ID) VALUES (3, 2, 1);
INSERT INTO PEDIDO_ARTICULO (CANTIDAD, ARTICULO_ID, PEDIDO_ID) VALUES (1, 1, 2);
INSERT INTO PEDIDO_ARTICULO (CANTIDAD, ARTICULO_ID, PEDIDO_ID) VALUES (1, 4, 2);
INSERT INTO PEDIDO_ARTICULO (CANTIDAD, ARTICULO_ID, PEDIDO_ID) VALUES (1, 6, 2);
INSERT INTO PEDIDO_ARTICULO (CANTIDAD, ARTICULO_ID, PEDIDO_ID) VALUES (1, 7, 3);


